<?php
/**************************************************
 * authentication result codes
 **************************************************/
define("A_AUTHENTICATE_SUCCESS", 200);
define("A_AUTHENTICATE_ERROR_INCOMPLETE_INPUT", 900);
define("A_AUTHENTICATE_ERROR_LOGIN_UNLISTED", 901);
define("A_AUTHENTICATE_ERROR_INCORRECT_PASSWORD", 902);
define("A_AUTHENTICATE_ERROR_LOGIN_DISABLED", 903);
define("A_AUTHENTICATE_ERROR_NO_CREDENTIALS_FOUND", 904);
define("A_AUTHENTICATE_ERROR_FUNCTION_DISALLOWED", 905);
define("A_AUTHENTICATE_ERROR_CLIENT_IP_NOT_FOUND", 906);
define("A_AUTHENTICATE_ERROR_CLIENT_IP_UNLISTED", 907);
define("A_AUTHENTICATE_ERROR_CLIENT_IP_DISABLED", 908);

define("R_REQUEST_VALID", 920);
define("R_REQUEST_BLOCKED_NO_SUCH_FUNCTION", 910);
define("R_REQUEST_BLOCKED_START_WAIT_TIME", 911);
define("R_REQUEST_BLOCKED_WITHIN_WAIT_TIME", 912);
define("R_REQUEST_BLOCKED_QUERY_ERROR", 913);
define("R_REQUEST_BLOCKING_LIFTED", 914);