<?php
define("P_CONFIG_FILE_READ_ERROR", 600);
define("P_ORACLE_DB_CONNECT_ERROR", 500);
define("P_MYSQL_DB_CONNECT_ERROR", 500);
define("P_PASSWORD_REQUIRED", 400);
define("P_ORACLE_DB_QUERY_ERROR", 500);
define("P_USERNAME_NOT_FOUND", 300);
define("P_PASSWORD_UPDATE_SUCCESS", 200);
define("P_PASSWORD_RESET_SUCCESS", 200);